// Labels comuns compartilhados entre cadernetas
const COMMON_LABELS = {
  data: 'DATA',
  pasto: 'PASTO',
  lote: 'LOTE',
  totalAnimais: 'TOTAL ANIMAIS',
  totalCabecas: 'TOTAL CABEÇAS',
}

// Labels específicos por caderneta
const MATERNIDADE_LABELS = {
  ...COMMON_LABELS,
  idCria: 'ID',
  brincoMae: 'ID BRINCO',
  chipMae: 'ID CHIP',
  sexo: 'SEXO',
  tipoParto: 'TIPO DE PARTO',
  raca: 'RAÇA',
  tratamento: 'TRATAMENTO',
  pesoCria: 'PESO CRIA',
  categoriaMae: 'CATEGORIA MÃE',
  escoreMatriz: 'ESCORE MATRIZ',
}

const PASTAGENS_LABELS = {
  ...COMMON_LABELS,
  manejador: 'MANEJADOR',
  numeroLote: 'NÚMERO LOTE',
  pastoSaida: 'PASTO SAÍDA',
  avaliacaoSaida: 'AVALIAÇÃO SAÍDA',
  tempoOcupacao: 'TEMPO OCUPAÇÃO',
  pastoSaidaAreaUtil: 'ÁREA ÚTIL (SAÍDA)',
  pastoSaidaEspecie: 'ESPÉCIE (SAÍDA)',
  pastoSaidaAlturaEntrada: 'ALTURA ENTRADA (SAÍDA)',
  pastoSaidaAlturaSaida: 'ALTURA SAÍDA (SAÍDA)',
  pastoEntrada: 'PASTO ENTRADA',
  avaliacaoEntrada: 'AVALIAÇÃO ENTRADA',
  tempoVedacao: 'TEMPO VEDAÇÃO',
  pastoEntradaAreaUtil: 'ÁREA ÚTIL (ENTRADA)',
  pastoEntradaEspecie: 'ESPÉCIE (ENTRADA)',
  pastoEntradaAlturaEntrada: 'ALTURA ENTRADA (ENTRADA)',
  pastoEntradaAlturaSaida: 'ALTURA SAÍDA (ENTRADA)',
  vaca: 'VACA',
  touro: 'TOURO',
  boiGordo: 'BOI GORDO',
  boiMagro: 'BOI MAGRO',
  garrote: 'GARROTE',
  bezerro: 'BEZERRO',
  novilha: 'NOVILHA',
  tropa: 'TROPA',
  outros: 'OUTROS',
  escoreGado: 'ESCORE DO GADO',
}

const RODEIO_LABELS = {
  ...COMMON_LABELS,
  numeroLote: 'NÚMERO LOTE',
  vaca: 'VACA',
  touro: 'TOURO',
  boiGordo: 'BOI GORDO',
  boiMagro: 'BOI MAGRO',
  garrote: 'GARROTE',
  bezerro: 'BEZERRO',
  novilha: 'NOVILHA',
  tropa: 'TROPA',
  outros: 'OUTROS',
  totalCabecas: 'N° CABEÇAS',
  escoreGadoIdeal: 'ESCORE GADO IDEAL',
  escoreGadoIdealObs: 'Observação',
  bebedourosCochos: 'BEBEDOUROS, COCHOS',
  bebedourosCochosObs: 'Observação',
  pastagensTaxaLotacao: 'PASTAGENS, TAXA DE LOTAÇÃO',
  pastagensTaxaLotacaoObs: 'Observação',
  animaisMachucadosDoentesBichados: 'ANIMAIS MACHUCADOS, DOENTES, BICHADOS',
  animaisMachucadosDoentesBichadosObs: 'Observação',
  cercasCochosPorteiras: 'CERCAS, COCHOS, PORTEIRAS',
  cercasCochosPorteirasObs: 'Observação',
  carrapatosMoscas: 'CARRAPATOS, MOSCAS',
  carrapatosMoscasObs: 'Observação',
  animaisEntreverados: 'ANIMAIS ENTREVERADOS',
  animaisEntreveradosObs: 'Observação',
  animalMorto: 'ANIMAL MORTO',
  animalMortoObs: 'Observação',
  escoreFezes: 'ESCORE FEZES',
  equipe: 'EQUIPE',
  escoreGado: 'ESCORE GADO',
}

const SUPLEMENTACAO_LABELS = {
  ...COMMON_LABELS,
  tratador: 'TRATADOR',
  numeroLote: 'N° LOTE',
  produto: 'SUPLEMENTO',
  gado: 'TIPO DE GADO',
  leitura: 'LEITURA DO COCHO',
  leituraCocho: 'LEITURA COCHO',
  kgCocho: 'SUPLEMENTO COCHO (KG)',
  kgDeposito: 'SUPLEMENTO DEPÓSITO (KG)',
  sacos: 'SACOS',
  suplementoQtd: 'SUPLEMENTO/QTD',
  limpezaCocho: 'LIMPEZA DE COCHO FOI REALIZADA?',
  limpezaCochoObs: 'Observação',
  cochosCondicoes: 'COCHOS ESTÃO EM BOAS CONDIÇÕES?',
  cochosCondicoesObs: 'Observação',
}

const BEBEDOUROS_LABELS = {
  ...COMMON_LABELS,
  responsavel: 'RESPONSÁVEL',
  numeroLote: 'NÚMERO LOTE',
  leituraBebedouro: 'LEITURA BEBEDOURO',
  numeroBebedouro: 'NÚMERO BEBEDOURO',
  categoria: 'CATEGORIA',
  observacao: 'OBSERVAÇÃO',
  aguaSuficiente: 'QUANTIDADE DE ÁGUA ESTÁ ADEQUADA?',
  aguaSuficienteObs: 'OBSERVAÇÃO ÁGUA SUFICIENTE',
  vazaoBebedouroIdeal: 'VAZÃO DA BÓIA ESTÁ IDEAL?',
  vazaoBebedouroIdealObs: 'OBSERVAÇÃO VAZÃO BEBEDOURO',
  aterroAcessoBebedouroIdeal: 'ATERRO/ACESSO AO BEBEDOURO ESTÁ ADEQUADO?',
  aterroAcessoBebedouroIdealObs: 'OBSERVAÇÃO ATERRO/ACESSO',
  espacamentoBebedouroIdeal: 'ESPAÇAMENTO BEBEDOURO IDEAL',
  espacamentoBebedouroIdealObs: 'OBSERVAÇÃO ESPAÇAMENTO',
  boiaProtecaoBoasCondicoes: 'BÓIA E PROTEÇÃO DA BÓIA ESTÃO EM BOAS CONDIÇÕES?',
  boiaProtecaoBoasCondicoesObs: 'OBSERVAÇÃO BÓIA E PROTEÇÃO',
}

const ABASTECIMENTO_LABELS = {
  ...COMMON_LABELS,
  quemAbasteceu: 'QUEM ABASTECEU',
  operadorMotorista: 'OPERADOR MOTORISTA',
  veiculoTrator: 'VEÍCULO TRATOR',
  placa: 'PLACA',
  hidrometroInicial: 'HIDRÔMETRO INICIAL',
  hidrometroFinal: 'HIDRÔMETRO FINAL',
  totalAbastecido: 'TOTAL ABASTECIDO',
  combustivel: 'COMBUSTÍVEL',
  odometro: 'ODÔMETRO',
  tipoOperacao: 'TIPO DE OPERAÇÃO',
  observacao: 'OBSERVAÇÃO',
}

const CANTINA_LABELS = {
  ...COMMON_LABELS,
  numeroCozinheiras: 'N° COZINHEIRAS',
  quemCozinhou: 'QUEM COZINHOU',
  quemAjudou: 'QUEM AJUDOU',
  numeroCafeManha: 'N° CAFÉ DA MANHÃ',
  numeroLanches: 'N° LANCHES',
  numeroRefeicoesAlmoco: 'N° REFEIÇÕES ALMOÇO',
  numeroRefeicoesJantar: 'N° REFEIÇÕES JANTAR',
  observacao: 'OBSERVAÇÃO',
}

const MOVIMENTACAO_LABELS = {
  ...COMMON_LABELS,
  loteOrigem: 'LOTE ORIGEM',
  loteDestino: 'DESTINO',
  numeroCabecas: 'NÚMERO CABEÇAS',
  pesoMedio: 'PESO MÉDIO (KG)',
  motivoMovimentacao: 'MOTIVO',
  brinco: 'BRINCO',
  chip: 'CHIP',
  brincoChip: 'BRINCO/CHIP',
  causaObservacao: 'CAUSA/OBSERVAÇÃO',
}

const ENFERMARIA_LABELS = {
  ...COMMON_LABELS,
  pasto: 'PASTO',
  lote: 'LOTE',
  brinco: 'ID. BRINCO',
  chip: 'ID. CHIP',
  brincoChip: 'BRINCO/CHIP',
  categoria: 'CATEGORIA',
  tratamento: 'TRATAMENTO',
  tratamentoOutros: 'Outros',
  pododermiteCascos: 'PODODERMITE DOS CASCOS',
  pododermiteCascosObs: 'OBSERVAÇÃO',
  sintomasPneumonia: 'SINTOMAS DE PNEUMONIA',
  sintomasPneumoniaObs: 'OBSERVAÇÃO',
  picadoCobra: 'PICADO POR COBRA',
  picadoCobraObs: 'OBSERVAÇÃO',
  incoordenacaoTremores: 'INCOORDENAÇÃO E TREMORES',
  incoordenacaoTremoresObs: 'OBSERVAÇÃO',
  febreAlta: 'FEBRE ALTA',
  febreAltaObs: 'OBSERVAÇÃO',
  presencaSangue: 'EXISTE ALGUM SANGRAMENTO',
  presencaSangueObs: 'OBSERVAÇÃO',
  fraturas: 'ALGUMA FRATURA / DESLOCAMENTO DE MEMBROS',
  fraturasObs: 'OBSERVAÇÃO',
  desordensDigestivas: 'DESORDENS DIGESTIVAS / TIMPANISMO / DIARREIA',
  desordensDigestivasObs: 'OBSERVAÇÃO',
}

const MORTE_LABELS = {
  ...COMMON_LABELS,
  pasto: 'PASTO',
  lote: 'LOTE',
  brinco: 'ID. BRINCO',
  chip: 'ID. CHIP',
  brincoChip: 'BRINCO/CHIP',
  categoria: 'CATEGORIA',
  categoriaOutros: 'CATEGORIA OUTROS',
  sexo: 'SEXO',
  raca: 'RAÇA',
  racaOutros: 'RAÇA OUTROS',
  idade: 'IDADE',
  pesoVivo: 'PESO VIVO',
  causaMorte: 'CAUSA DA MORTE',
  causaMorteOutros: 'CAUSA DA MORTE OUTROS',
  secrecaoOrificios: 'ALGUMA SECREÇÃO NOS ORIFÍCIOS',
  secrecaoOrificiosObs: 'OBSERVAÇÃO',
  sintomasPneumonia: 'SINTOMAS DE PNEUMONIA',
  sintomasPneumoniaObs: 'OBSERVAÇÃO',
  inchaco: 'EXISTE ALGUM SANGRAMENTO',
  inchacoObs: 'OBSERVAÇÃO',
  incoordenacaoTremores: 'INCOORDENAÇÃO / PEDALAGEM E TREMORES MUSCULARES DA MORTE',
  incoordenacaoTremoresObs: 'OBSERVAÇÃO',
  apatiaFraqueza: 'APATIA OU FRAQUEZA',
  apatiaFraquezaObs: 'OBSERVAÇÃO',
  desordensDigestivas: 'DESORDENS DIGESTIVAS / TIMPANISMO / DIARREIA',
  desordensDigestivasObs: 'OBSERVAÇÃO',
  fraturas: 'ALGUMA FRATURA / DESLOCAMENTO DE MEMBROS',
  fraturasObs: 'OBSERVAÇÃO',
  decomposicao: 'ANIMAL EM DECOMPOSIÇÃO / PUTREFAÇÃO',
  decomposicaoObs: 'OBSERVAÇÃO',
}

const CLIMA_LABELS = {
  ...COMMON_LABELS,
  responsavel: 'RESPONSÁVEL',
  temperaturaMedia: 'TEMPERATURA MÉDIA (°C)',
  observacao: 'OBSERVAÇÃO',
}

const ENTRADA_INSUMOS_LABELS = {
  dataEntrada: 'DATA DE ENTRADA',
  horario: 'HORÁRIO',
  produto: 'PRODUTO',
  quantidade: 'QUANTIDADE (kg)',
  valorUnitario: 'VALOR UNITÁRIO (R$/kg)',
  valorTotal: 'VALOR TOTAL (R$)',
  notaFiscal: 'N° NOTA FISCAL',
  fornecedor: 'FORNECEDOR',
  placa: 'PLACA',
  motorista: 'MOTORISTA',
  responsavelRecebimento: 'RESPONSÁVEL RECEBIMENTO',
}

const SAIDA_INSUMOS_LABELS = {
  dataProducao: 'DATA DE PRODUÇÃO',
  dietaProduzida: 'DIETA PRODUZIDA',
  destinoProducao: 'DESTINO DA PRODUÇÃO',
  totalProduzido: 'TOTAL PRODUZIDO (kg)',
}

const INSUMOS_POR_SAIDA_LABELS = {
  idSaida: 'ID DA SAÍDA',
  dataProducao: 'DATA DE PRODUÇÃO',
  dietaProduzida: 'DIETA PRODUZIDA',
  insumo: 'INSUMO',
  quantidade: 'QUANTIDADE (kg)',
}

// Exportar objeto principal
export const LABELS_BY_CADERNETA: Record<string, Record<string, string>> = {
  maternidade: MATERNIDADE_LABELS,
  pastagens: PASTAGENS_LABELS,
  rodeio: RODEIO_LABELS,
  suplementacao: SUPLEMENTACAO_LABELS,
  bebedouros: BEBEDOUROS_LABELS,
  abastecimento: ABASTECIMENTO_LABELS,
  cantina: CANTINA_LABELS,
  movimentacao: MOVIMENTACAO_LABELS,
  enfermaria: ENFERMARIA_LABELS,
  morte: MORTE_LABELS,
  clima: CLIMA_LABELS,
  'entrada-insumos': ENTRADA_INSUMOS_LABELS,
  'saida-insumos': SAIDA_INSUMOS_LABELS,
  'insumos-por-saida': INSUMOS_POR_SAIDA_LABELS,
}
