// Labels comuns compartilhados entre cadernetas
const COMMON_LABELS = {
  data: 'DATA',
  pasto: 'PASTO',
  lote: 'LOTE',
  totalAnimais: 'TOTAL ANIMAIS',
  totalCabecas: 'TOTAL CABEÇAS',
}

// Labels específicos por caderneta
const MATERNIDADE_LABELS = {
  ...COMMON_LABELS,
  numeroCria: 'NÚMERO CRIA',
  numeroMae: 'NÚMERO MÃE',
  sexo: 'SEXO',
  tipoParto: 'TIPO DE PARTO',
  raca: 'RAÇA',
  tratamento: 'TRATAMENTO',
  pesoCria: 'PESO CRIA',
  categoriaMae: 'CATEGORIA MÃE',
  escoreMatriz: 'ESCORE MATRIZ',
}

const PASTAGENS_LABELS = {
  ...COMMON_LABELS,
  manejador: 'MANEJADOR',
  numeroLote: 'NÚMERO LOTE',
  pastoSaida: 'PASTO SAÍDA',
  avaliacaoSaida: 'AVALIAÇÃO SAÍDA',
  tempoOcupacao: 'TEMPO OCUPAÇÃO',
  pastoSaidaAreaUtil: 'ÁREA ÚTIL (SAÍDA)',
  pastoSaidaEspecie: 'ESPÉCIE (SAÍDA)',
  pastoSaidaAlturaEntrada: 'ALTURA ENTRADA (SAÍDA)',
  pastoSaidaAlturaSaida: 'ALTURA SAÍDA (SAÍDA)',
  pastoEntrada: 'PASTO ENTRADA',
  avaliacaoEntrada: 'AVALIAÇÃO ENTRADA',
  tempoVedacao: 'TEMPO VEDAÇÃO',
  pastoEntradaAreaUtil: 'ÁREA ÚTIL (ENTRADA)',
  pastoEntradaEspecie: 'ESPÉCIE (ENTRADA)',
  pastoEntradaAlturaEntrada: 'ALTURA ENTRADA (ENTRADA)',
  pastoEntradaAlturaSaida: 'ALTURA SAÍDA (ENTRADA)',
  vaca: 'VACA',
  touro: 'TOURO',
  boiGordo: 'BOI GORDO',
  boiMagro: 'BOI MAGRO',
  garrote: 'GARROTE',
  bezerro: 'BEZERRO',
  novilha: 'NOVILHA',
  tropa: 'TROPA',
  outros: 'OUTROS',
  escoreGado: 'ESCORE DO GADO',
}

const RODEIO_LABELS = {
  ...COMMON_LABELS,
  numeroLote: 'NÚMERO LOTE',
  vaca: 'VACA',
  touro: 'TOURO',
  boiGordo: 'BOI GORDO',
  boiMagro: 'BOI MAGRO',
  garrote: 'GARROTE',
  bezerro: 'BEZERRO',
  novilha: 'NOVILHA',
  tropa: 'TROPA',
  outros: 'OUTROS',
  totalCabecas: 'N° CABEÇAS',
  escoreGadoIdeal: 'ESCORE GADO IDEAL',
  escoreGadoIdealObs: 'Observação',
  aguaBoaBebedouro: 'ÁGUA BOA BEBEDOURO',
  aguaBoaBebedouroObs: 'Observação',
  pastagemAdequada: 'PASTAGEM ADEQUADA',
  pastagemAdequadaObs: 'Observação',
  animaisDoentes: 'ANIMAIS DOENTES / BICHADOS',
  animaisDoentesObs: 'Observação',
  cercasCochos: 'CERCAS, COCHOS',
  cercasCochosObs: 'Observação',
  carrapatosMoscas: 'CARRAPATOS, MOSCAS',
  carrapatosMoscasObs: 'Observação',
  animaisEntreverados: 'ANIMAIS ENTREVERADOS',
  animaisEntreveradosObs: 'Observação',
  animalMorto: 'ANIMAL MORTO',
  animalMortoObs: 'Observação',
  escoreFezes: 'ESCORE FEZES',
  equipe: 'EQUIPE',
  escoreGado: 'ESCORE GADO',
}

const SUPLEMENTACAO_LABELS = {
  ...COMMON_LABELS,
  tratador: 'TRATADOR',
  numeroLote: 'N° LOTE',
  produto: 'SUPLEMENTO',
  gado: 'TIPO DE GADO',
  recria: 'CREEP',
  leitura: 'LEITURA DO COCHO',
  leituraCocho: 'LEITURA COCHO',
  creepKg: 'CREEP (KG)',
  kgCocho: 'SUPLEMENTO COCHO (KG)',
  kgDeposito: 'SUPLEMENTO DEPÓSITO (KG)',
  sacos: 'SACOS',
  suplementoQtd: 'SUPLEMENTO/QTD',
}

const BEBEDOUROS_LABELS = {
  ...COMMON_LABELS,
  responsavel: 'RESPONSÁVEL',
  numeroLote: 'NÚMERO LOTE',
  leituraBebedouro: 'LEITURA BEBEDOURO',
  numeroBebedouro: 'NÚMERO BEBEDOURO',
  categoria: 'CATEGORIA',
  observacao: 'OBSERVAÇÃO',
  aguaSuficiente: 'ÁGUA SUFICIENTE',
  aguaSuficienteObs: 'OBSERVAÇÃO ÁGUA SUFICIENTE',
  vazaoBebedouroIdeal: 'VAZÃO BEBEDOURO IDEAL',
  vazaoBebedouroIdealObs: 'OBSERVAÇÃO VAZÃO BEBEDOURO',
  aterroAcessoBebedouroIdeal: 'ATERRO/ACESSO BEBEDOURO IDEAL',
  aterroAcessoBebedouroIdealObs: 'OBSERVAÇÃO ATERRO/ACESSO',
  espacamentoBebedouroIdeal: 'ESPAÇAMENTO BEBEDOURO IDEAL',
  espacamentoBebedouroIdealObs: 'OBSERVAÇÃO ESPAÇAMENTO',
  boiaProtecaoBoasCondicoes: 'BÓIA E PROTEÇÃO EM BOAS CONDIÇÕES',
  boiaProtecaoBoasCondicoesObs: 'OBSERVAÇÃO BÓIA E PROTEÇÃO',
}

const MOVIMENTACAO_LABELS = {
  ...COMMON_LABELS,
  loteOrigem: 'LOTE ORIGEM',
  loteDestino: 'DESTINO',
  numeroCabecas: 'NÚMERO CABEÇAS',
  pesoMedio: 'PESO MÉDIO',
  motivoMovimentacao: 'MOTIVO',
  brinco: 'BRINCO',
  chip: 'CHIP',
  brincoChip: 'BRINCO/CHIP',
  causaObservacao: 'CAUSA/OBSERVAÇÃO',
}

const ENFERMARIA_LABELS = {
  ...COMMON_LABELS,
  pasto: 'PASTO',
  lote: 'LOTE',
  brinco: 'BRINCO',
  chip: 'CHIP',
  brincoChip: 'BRINCO/CHIP',
  categoria: 'CATEGORIA',
  tratamento: 'TRATAMENTO',
  tratamentoOutros: 'Outros',
  problemaCasco: 'PROBLEMA DE CASCO',
  problemaCascoObs: 'OBSERVAÇÃO',
  sintomasPneumonia: 'SINTOMAS PNEUMONIA',
  sintomasPneumoniaObs: 'OBSERVAÇÃO',
  picadoCobra: 'PICADO POR COBRA',
  picadoCobraObs: 'OBSERVAÇÃO',
  incoordenacaoTremores: 'INCOORDENAÇÃO E TREMORES',
  incoordenacaoTremoresObs: 'OBSERVAÇÃO',
  febreAlta: 'FEBRE ALTA',
  febreAltaObs: 'OBSERVAÇÃO',
  presencaSangue: 'PRESENÇA DE SANGUE',
  presencaSangueObs: 'OBSERVAÇÃO',
  fraturas: 'FRATURAS',
  fraturasObs: 'OBSERVAÇÃO',
  desordensDigestivas: 'DESORDENS DIGESTIVAS',
  desordensDigestivasObs: 'OBSERVAÇÃO',
}

const MORTE_LABELS = {
  ...COMMON_LABELS,
  pasto: 'PASTO',
  lote: 'LOTE',
  brinco: 'BRINCO',
  chip: 'CHIP',
  brincoChip: 'BRINCO/CHIP',
  vaca: 'VACA',
  touro: 'TOURO',
  boiGordo: 'BOI GORDO',
  boiMagro: 'BOI MAGRO',
  garrote: 'GARROTE',
  bezerro: 'BEZERRO',
  novilha: 'NOVILHA',
  tropa: 'TROPA',
  outros: 'OUTROS',
  sexo: 'SEXO',
  raca: 'RAÇA',
  idade: 'IDADE',
  pesoVivo: 'PESO VIVO',
  causaMorte: 'CAUSA DA MORTE',
  secrecaoOrificios: 'SECREÇÃO EM ORIFÍCIOS',
  secrecaoOrificiosObs: 'OBSERVAÇÃO',
  sintomasPneumonia: 'SINTOMAS DE PNEUMONIA',
  sintomasPneumoniaObs: 'OBSERVAÇÃO',
  inchaco: 'INCHAÇO',
  inchacoObs: 'OBSERVAÇÃO',
  incoordenacaoTremores: 'INCOORDENAÇÃO/TREMORES',
  incoordenacaoTremoresObs: 'OBSERVAÇÃO',
  apatiaFraqueza: 'APATIA/FRAQUEZA',
  apatiaFraquezaObs: 'OBSERVAÇÃO',
  presencaSangue: 'PRESENÇA DE SANGUE',
  presencaSangueObs: 'OBSERVAÇÃO',
  desordensDigestivas: 'DESORDENS DIGESTIVAS',
  desordensDigestivasObs: 'OBSERVAÇÃO',
}

const CLIMA_LABELS = {
  ...COMMON_LABELS,
  responsavel: 'RESPONSÁVEL',
  temperaturaMedia: 'TEMPERATURA MÉDIA (°C)',
  observacao: 'OBSERVAÇÃO',
}

const ENTRADA_INSUMOS_LABELS = {
  dataEntrada: 'DATA DE ENTRADA',
  horario: 'HORÁRIO',
  produto: 'PRODUTO',
  quantidade: 'QUANTIDADE (kg)',
  valorUnitario: 'VALOR UNITÁRIO (R$/kg)',
  valorTotal: 'VALOR TOTAL (R$)',
  notaFiscal: 'N° NOTA FISCAL',
  fornecedor: 'FORNECEDOR',
  placa: 'PLACA',
  motorista: 'MOTORISTA',
  responsavelRecebimento: 'RESPONSÁVEL RECEBIMENTO',
}

const SAIDA_INSUMOS_LABELS = {
  dataProducao: 'DATA DE PRODUÇÃO',
  dietaProduzida: 'DIETA PRODUZIDA',
  destinoProducao: 'DESTINO DA PRODUÇÃO',
  totalProduzido: 'TOTAL PRODUZIDO (kg)',
}

const INSUMOS_POR_SAIDA_LABELS = {
  idSaida: 'ID DA SAÍDA',
  dataProducao: 'DATA DE PRODUÇÃO',
  dietaProduzida: 'DIETA PRODUZIDA',
  insumo: 'INSUMO',
  quantidade: 'QUANTIDADE (kg)',
}

// Exportar objeto principal
export const LABELS_BY_CADERNETA: Record<string, Record<string, string>> = {
  maternidade: MATERNIDADE_LABELS,
  pastagens: PASTAGENS_LABELS,
  rodeio: RODEIO_LABELS,
  suplementacao: SUPLEMENTACAO_LABELS,
  bebedouros: BEBEDOUROS_LABELS,
  movimentacao: MOVIMENTACAO_LABELS,
  enfermaria: ENFERMARIA_LABELS,
  morte: MORTE_LABELS,
  clima: CLIMA_LABELS,
  'entrada-insumos': ENTRADA_INSUMOS_LABELS,
  'saida-insumos': SAIDA_INSUMOS_LABELS,
  'insumos-por-saida': INSUMOS_POR_SAIDA_LABELS,
}
